name: Call Reusable Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build and test'
        required: true
        type: string

jobs:
  call-reusable:
    uses: ./.github/workflows/resusable-workflow.yaml
    with:
      environment: ${{ inputs.environment }}
